CREATE OR REPLACE VIEW p_datasources AS
SELECT ds.p_id,
       ds.p_filepath,
       ds.id,
       ds.name,
       ds.repository_url,
       ds.owner_id,
       ds.created_at,
       ds.updated_at,
       ds.project_id,
       ds.size,
       ds.lock_version,
       ds.state,
       ds.db_class,
       ds.db_name,
       ds.table_name,
       ds.site_id,
       ds.revision,
       ds.repository_data_id,
       ds.repository_extract_data_id,
       ds.embedded,
       ds.incrementable_extracts,
       ds.refreshable_extracts,
       ds.data_engine_extracts,
       ds.extracts_refreshed_at,
       ds.first_published_at,
       ds.connectable,
       ds.is_hierarchical,
       ds.extracts_incremented_at,
       ds.luid,
       ds.asset_key_id,
       ds.document_version,
       ds.description,
       ds.content_version,
       ds.p_cre_date,
       ds.p_active_flag,
       ds.p_valid_from,
       ds.p_valid_to,
       ds.parent_workbook_id,
       ds.last_published_at,
       ((p.name::text || ' ('::text) || p.id::text) || ')'::text AS project_name_id, 
       ((s.name::text || ' ('::text) || s.id::text) || ')'::text AS site_name_id, 
       ((wb_su.name::text || ' ('::text) || ds.owner_id::text) || ')'::text AS publisher_name_id, 
       ((ds.name::text || ' ('::text) || ds.id::text) || ')'::text AS workbook_name_id, 
       'DATASOURCE'::text AS type
FROM palette.h_datasources ds
left outer join palette.h_projects p on (p.id = ds.project_id and p.site_id = ds.site_id and least(ds.p_valid_to, p.p_valid_to) >= greatest(ds.p_valid_from, p.p_valid_from))
left outer join palette.h_sites s on (s.id = ds.site_id and least(ds.p_valid_to, s.p_valid_to) >= greatest(ds.p_valid_from, s.p_valid_from))
left outer join palette.h_users wb_u on (wb_u.id  = ds.owner_id and wb_u.site_id = ds.site_id and least(ds.p_valid_to, wb_u.p_valid_to) >= greatest(ds.p_valid_from, wb_u.p_valid_from))
left outer join palette.h_system_users wb_su on (wb_su.id = wb_u.system_user_id and least(ds.p_valid_to, wb_su.p_valid_to) >= greatest(ds.p_valid_from, wb_su.p_valid_from))
group by
       ds.p_id,
       ds.p_filepath,
       ds.id,
       ds.name,
       ds.repository_url,
       ds.owner_id,
       ds.created_at,
       ds.updated_at,
       ds.project_id,
       ds.size,
       ds.lock_version,
       ds.state,
       ds.db_class,
       ds.db_name,
       ds.table_name,
       ds.site_id,
       ds.revision,
       ds.repository_data_id,
       ds.repository_extract_data_id,
       ds.embedded,
       ds.incrementable_extracts,
       ds.refreshable_extracts,
       ds.data_engine_extracts,workbook_name_id, 
       ds.extracts_refreshed_at,
       ds.first_published_at,
       ds.connectable,
       ds.is_hierarchical,
       ds.extracts_incremented_at,
       ds.luid,
       ds.asset_key_id,
       ds.document_version,
       ds.description,
       ds.content_version,
       ds.p_cre_date,
       ds.p_active_flag,
       ds.p_valid_from,
       ds.p_valid_to,
       ds.parent_workbook_id,
       ds.last_published_at,
       ((p.name::text || ' ('::text) || p.id::text) || ')'::text , 
       ((s.name::text || ' ('::text) || s.id::text) || ')'::text , 
       ((wb_su.name::text || ' ('::text) || ds.owner_id::text) || ')'::text , 
       ((ds.name::text || ' ('::text) || ds.id::text) || ')'::text,
       'DATASOURCE'::text
;
