language: bash
# install the RPM package
addons:
  apt:
    packages:
      - rpm
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass

env:
  global:
  # travis encrypt DEPLOY_PASS=...
  - secure: "qZfId4hpkMx9LIJcdYISR/sDB2yBEQ8sZupqOFMQvW2UK49pSWNE5kiPSohpPT/P8X485ZTsfZztD8/enIVXZhswwHBqQyyslU4NcCDyNG0caMEWFx9kElpONSgcRrwgkRks+4HX3JhzEWgN9dmpgW1HBsNCzbSwFqMp4WS5+kSCWIbvVLIDLt7rxBO7EyIRIOq3iyrBdBugH26OjkeZfTqGLIRZ7koFXorWtf8K6lfwjHaZ9Z6BgytFPQNunqluqenvLRh0vT8T+c6gWcqIfTyu6BWq5HtBBSgr9Mqgo8zJCdYNAEkaB6IbWG8/bRrMNdBdxPKsHAOJKUW0W8OyNZltPy/+fgOVXOZo+0+WXbKjvDqKvoVDoOxToizlJAE8R4DHEJBZGhOFmUlo8yoNB0vpbUF8O4rLDdjqQ0ySwOJk1+ADm3jk8Ahsj6RzrC0GRyUsy1SX9vkMseDTegYIdJx6PFv1CJEXKVI7EKjhITKft96lPBSdz4DOV4VFK/KRYOrYf3uLQcbl52xQuAhSjusT9Dc0O1CwKayA3kWVNH+nb/Df4dMOBIoAvH/PLwrvmldMqdYsFuQ+3f41FmhBQxOKPRu8QdBpkFRcIlMYDGWJP1qJLaw9FIsTOsxI/GbyJbgLV8DWC1OOPEmwaxuWwDjPMKAbnjYy5gxZLiJI1nc="

  - FULL_INSTALL_ZIP=palette-insight-reporting-$TRAVIS_TAG-full-install.zip
  - INCREMENTAL_INSTALL_ZIP=palette-insight-reporting-$TRAVIS_TAG-install.zip
  - PACKED_ZIP=palette-insight-reporting--packed--$TRAVIS_TAG.zip

  - CURRENT_VERSION_FULL_INSTALL_DIR=_root/opt/palette-insight-reporting/full-installs/$TRAVIS_TAG

  # DEPLOYMENT DATA
  - DEPLOY_HOST=rpm.palette-software.com
  - DEPLOY_PATH=/var/palette-rpm-repo
  - DEPLOY_USER=palette-rpm

script:
  # Determine version number
  - VERSION_FROM_TRAVIS=$(echo $TRAVIS_TAG | grep -o '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\(\.[0-9][0-9]\)*')
  - LATEST_MIGRATION_VERSION=$(./maxversion.sh)
  - VERSION=${VERSION:-$VERSION_FROM_TRAVIS}
  - VERSION=${VERSION:-$LATEST_MIGRATION_VERSION} # When build is not tagged
  - export VERSION

  - _scripts/build.sh
  - _scripts/rpm.sh

before_deploy:
  # Upload the RPM to the RPM repository
  # by exportin it to SSHPASS, sshpass wont log the command line and the password
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r rpm-build/_build/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

  # Update the RPM repository
  - export DEPLOY_CMD="createrepo ${DEPLOY_PATH}/"
  - sshpass -e ssh  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_CMD

deploy:
  provider: releases
  draft: false
  prerelease: false
  api_key:
    secure: qVurNxNaTatjAER0EHig4UYPAAYg4EvUbcwoEBRqcpgZRXCtz4bxHNzHn65PRmqYOJNaAjxm8pYfxM/+up7eqABV3vD8q5LOQz42y7Gl6lESq7X+CJ4C9xqW0UEcg6/AiWgQLLM4hceloOEpOQirOTv3+SdCuUdZfREW1lfvFggXQRrFmgX9GU8GsaV59F6XscSHvur0GCKNzrxUwTl8EYWFDmy3+o2xTyLCMM3u8udsLQ76PijcWTT4eXoA6eryW4CGjq9L4QpSorq38lKVlEtxjt1Jo4GeUaOpoyrTy2tgwP9aNnTdLbWov6oRN6R8geVp2gdgV376O5nyJnukxHxlMbtAX8oPNext547WTT8pewv8+JvahasczPHhWku4koRBK7enXFnzkrj2D431SIUhra1BWym6Uk9WU82B8glqmon1BWp2uSh5L7AQ2ys1cZ1NimS9DMJ6e3+o/HBfqFhh+lSKuHhI1m7Q8i8C0uT+nCFNXwotWQ+kFlpWS2CR3zXu/iShOleEt7us1EV7SeEwXRVBua6dFyJIicP7SOlFmA5EbN0vILpVkS0GpSTQZ70k7BTlCakiNRBDj3SfE2RLIpJ3NYLre0+Xh6Of+puRPVmI4a7gJ5ANeVbc60lvHTFFjvCNNQQhOb3vNqdYBp/C3TxQTF3BS2SgyRaaOYE=
  file:
    - "$FULL_INSTALL_ZIP"
    - "$INCREMENTAL_INSTALL_ZIP"
    - "$PACKED_ZIP"
  on:
    repo: palette-software/insight-data-model
    tags: true
  skip_cleanup: true
notifications:
  email:
    on_success: never
    on_failure: never
