env:
  global:
  - FULL_INSTALL_ZIP=insight-data-model-$TRAVIS_TAG-full-install.zip
  - INCREMENTAL_INSTALL_ZIP=insight-data-model-$TRAVIS_TAG-install.zip
  - PACKED_ZIP=insight-data-model--packed--$TRAVIS_TAG.zip

  - CURRENT_VERSION_FULL_INSTALL_DIR=_root/opt/insight-data-model/full-installs/$TRAVIS_TAG


  # DEPLOYMENT DATA
  - DEPLOY_HOST=rpm.palette-software.net
  - DEPLOY_PATH=/var/palette-rpm-repo
  - DEPLOY_USER=palette-rpm
  - DEPLOY_KEY=deploy_key

script:
  - echo "Nothing to build. Done."

# install the RPM package
addons:
  apt:
    packages:
      - rpm

before_install:

before_deploy:
  # Create the full installer
  - sed -i "s/#version_number#/$TRAVIS_TAG/g" ./full_install.sql
  - cat full_install.sql
  - zip -r -j $FULL_INSTALL_ZIP functions/*.sql tables/*.sql tables/*.SQL views/*.sql full_install.sql full_install.sh

  # Create the incremental installer
  - export LATEST_MIGRATION_VERSION=`./maxversion.sh`
  - echo "$LATEST_MIGRATION_VERSION"
  - zip -r -j $INCREMENTAL_INSTALL_ZIP migrations/$LATEST_MIGRATION_VERSION/*.sql

  # Build the RPM file
  - export VERSION=$(echo $TRAVIS_TAG | grep -o '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\(\.[0-9][0-9]\)*')
  - echo "Building RPM version $VERSION"
  - pushd rpm-build

  # Create directories
  - mkdir -p _root/opt/insight-data-model/full-installs
  - mkdir -p _root/opt/insight-data-model/migrations
  - mkdir -p _build

  # As dirs +1 returns paths with a tilde in them, we need to expand it
  - export SRC_DIR=$(eval echo `dirs +1`)

  # Copy over the full install versions
  - cp -Rv $SRC_DIR/full-installs/v* _root/opt/insight-data-model/full-installs

  # Copy over the migrations
  - cp -Rv $SRC_DIR/migrations/v* _root/opt/insight-data-model/migrations

  # Clean the destination for the current version
  - rm -rfv $CURRENT_VERSION_FULL_INSTALL_DIR

  # Overwrite the currently tagged versions directory with the
  - unzip $SRC_DIR/$FULL_INSTALL_ZIP -d $CURRENT_VERSION_FULL_INSTALL_DIR

  # Copy the shell script over
  - cp -v $SRC_DIR/insight-datamodel-install.sh _root/opt/insight-data-model

  # Pack the rpm archvie
  - rpmbuild -bb --buildroot "$(pwd)/_root" --define "_rpmdir $(pwd)/_build" --define "version $VERSION" --define "buildrelease $TRAVIS_BUILD_NUMBER" insight-data-model.spec

  # Pack it as a zip also
  - zip -r $SRC_DIR/$PACKED_ZIP _root/opt/insight-data-model

  # Decrypt the SSH key for deployment
  - openssl aes-256-cbc -K $encrypted_9fbb5ae586fd_key -iv $encrypted_9fbb5ae586fd_iv -in ../deploy_key.enc -out $DEPLOY_KEY -d

  # kill openssl warnings because of bad permissions
  - chmod 600 $DEPLOY_KEY

  # Upload the RPM to the RPM repository
  # by exportin it to SSHPASS, sshpass wont log the command line and the password
  - echo "scp -i $DEPLOY_KEY -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r _build/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
  - scp -i $DEPLOY_KEY -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r _build/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

  # Update the RPM repository
  - export DEPLOY_CMD="createrepo $DEPLOY_PATH/"
  - ssh -i $DEPLOY_KEY  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_CMD

  # Go back to the original root dir, so travis can find the zip files
  - popd

deploy:
  provider: releases
  draft: false
  prerelease: true
  api_key:
    secure: qVurNxNaTatjAER0EHig4UYPAAYg4EvUbcwoEBRqcpgZRXCtz4bxHNzHn65PRmqYOJNaAjxm8pYfxM/+up7eqABV3vD8q5LOQz42y7Gl6lESq7X+CJ4C9xqW0UEcg6/AiWgQLLM4hceloOEpOQirOTv3+SdCuUdZfREW1lfvFggXQRrFmgX9GU8GsaV59F6XscSHvur0GCKNzrxUwTl8EYWFDmy3+o2xTyLCMM3u8udsLQ76PijcWTT4eXoA6eryW4CGjq9L4QpSorq38lKVlEtxjt1Jo4GeUaOpoyrTy2tgwP9aNnTdLbWov6oRN6R8geVp2gdgV376O5nyJnukxHxlMbtAX8oPNext547WTT8pewv8+JvahasczPHhWku4koRBK7enXFnzkrj2D431SIUhra1BWym6Uk9WU82B8glqmon1BWp2uSh5L7AQ2ys1cZ1NimS9DMJ6e3+o/HBfqFhh+lSKuHhI1m7Q8i8C0uT+nCFNXwotWQ+kFlpWS2CR3zXu/iShOleEt7us1EV7SeEwXRVBua6dFyJIicP7SOlFmA5EbN0vILpVkS0GpSTQZ70k7BTlCakiNRBDj3SfE2RLIpJ3NYLre0+Xh6Of+puRPVmI4a7gJ5ANeVbc60lvHTFFjvCNNQQhOb3vNqdYBp/C3TxQTF3BS2SgyRaaOYE=
  file:
    - "$FULL_INSTALL_ZIP"
    - "$INCREMENTAL_INSTALL_ZIP"
    - "$PACKED_ZIP"
  on:
    repo: palette-software/insight-data-model
    tags: true
  skip_cleanup: true
notifications:
  email:
    on_success: never
    on_failure: never
