language: bash
# install the RPM package
addons:
  apt:
    packages:
      - rpm
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass

env:
  global:
  # travis encrypt DEPLOY_PASS=...
  - secure: "DY/M0ppH1NHjuTFjwkdk3QiZRBR0nXIsctmyQysnfAijOwRb4oRhq90CG1FSsunWSUG8PA9Q99588PbzscXo3YnRIku0eTixjNfpvWTFU6dxUpPw6eIZFkt9Ie1DlrNBxaEUwAUHTODU8pPIfYSuzNzDbB5nA9RHYjtwSEXRcLlFcPi5BEa2aznIbMo6Zfqq38INU7nHOWlwvnaWSEE0WPYloF7kJSsTYrjZdEL8+bMM7B6MBs/c7T6eGoSNDKpXZEf1o7tzW0DpcqnRu6UcRz+3nvDV3snq6HiyEkgeXW+MDIiNKgUgqXc+RsgeAXEx4AqmwkXnHSg2ZfABBt2evhhAEZ16OaecAUupvoev4dvAALd3mbaU0fGrU/lHXdQsyikN4++voKkrIsAwhAa8/KdJUCbGnb1JibPrBLPLpvv4W5Ogi1dOe8hvpM40RhvqGzruzsTf+wvNEaVpwKJdUh004KzTbvc/MLiAMR/8DVUwQI7CtT6cpk0KN7FkV+b0xV8RptQCCEXkfHQQBH69H3g3JP4A7YMxgo5HoXtMXGsvYgJz1tg2zT2kb0xB/jJYWWy7w/I9QbMn8y56sSU49DJlRW7m1n8+WLnNKQkvOkSRKJPhTvHvLUWjZ7MkDXtBOHbygECLXV5pcCBPAeQlOJ2UAfcHRG5vLIyjFhbPCUQ="

  - FULL_INSTALL_ZIP=palette-insight-reporting-$TRAVIS_TAG-full-install.zip
  - INCREMENTAL_INSTALL_ZIP=palette-insight-reporting-$TRAVIS_TAG-install.zip
  - PACKED_ZIP=palette-insight-reporting--packed--$TRAVIS_TAG.zip

  - CURRENT_VERSION_FULL_INSTALL_DIR=_root/opt/palette-insight-reporting/full-installs/$TRAVIS_TAG

  # DEPLOYMENT DATA
  - DEPLOY_HOST=rpm.palette-software.net
  - DEPLOY_PATH=/var/palette-rpm-repo
  - DEPLOY_USER=palette-rpm

script:
  # Determine version number
  - VERSION_FROM_TRAVIS=$(echo "${TRAVIS_TAG}" | grep -o '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\(\.[0-9][0-9]\)*' || true)
  - LATEST_MIGRATION_VERSION=$(./maxversion.sh)
  - VERSION=${VERSION:-$VERSION_FROM_TRAVIS}
  - VERSION=${VERSION:-$LATEST_MIGRATION_VERSION} # When build is not tagged
  - export VERSION

  - scripts/build.sh
  - scripts/rpm.sh

before_deploy:
  # Upload the RPM to the RPM repository
  # by exportin it to SSHPASS, sshpass wont log the command line and the password
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r rpm-build/_build/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

  # Update the RPM repository
  - export DEPLOY_CMD="createrepo ${DEPLOY_PATH}/"
  - sshpass -e ssh  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_CMD

deploy:
  provider: releases
  draft: false
  prerelease: false
  api_key:
    secure: "NLC/SYeO8FygxYfmmHwDrBqVdOHPfwHjzuKbgmLL7c8AEixl7oT4p76euPBN2XpKvo04VTEyMcjpzwRIgxOwTAT4IqiFi5b3w1q3j5EuNBwBQrhPSchJhFssYMutzDNEQ2hTqzQ4ChEHWfXcYLlsMVnuTrJm9ZEm6GcCipxr+PlLHOY94hVhr4wwJFseqS+5P3Hmqva4+Ea9VyONbLYKMCGLLBZyKrhWHnh2AWU/+HjsKaN2tWOwLDOjl71CWuHSU+Im1ZBTX+F8BVuEqQouM+5rpdTTLJsxCK6RRDnYC/acAY1CQejAXhOxZawyXBfA62mt/t+nIVoilZsQJKUG9eqcTBl7etSfYNOf43Cj2/nhlH3Db9zswfL8haCmF/nvQ+bmG97HaknpQh3VQOFPOhE5u9v+q2wb+l62SLpGlbBVfd4pJMDaCXN/B25oTUymM9Rr/7nMdCxWUmnsVM9nlbn/OCGyBGxPEqynXbJHV7mojmkihoI6/zlEBin4Ori9V3GFy4l4Efrl92PmRAxpJYU1YSMJmKASrUOI8J0wdfd2DwnqDox/9eMMxXii0lB/ZO2DXyqjsM/u1BeXRlhSC124jSL+CF5oOx4WL8FTUMuDcjUZChML6zPaVQegToULp4Q0cMwax7xcgwuXmNXyNf+YEKGi2lDTdktdNHWZnYs="
  file:
    - "$FULL_INSTALL_ZIP"
    - "$INCREMENTAL_INSTALL_ZIP"
    - "$PACKED_ZIP"
  on:
    repo: palette-software/insight-data-model
    tags: true
  skip_cleanup: true
notifications:
  email:
    on_success: never
    on_failure: never
