env:
  global:
  - FULL_INSTALL_ZIP=palette-insight-reporting-$TRAVIS_TAG-full-install.zip
  - INCREMENTAL_INSTALL_ZIP=palette-insight-reporting-$TRAVIS_TAG-install.zip
script:
- echo "Nothing to build. Done."
before_deploy:
  # Create the full installer
- sed -i "s/#version_number#/$TRAVIS_TAG/g" ./full_install.sql
- cat full_install.sql
- zip -r -j $FULL_INSTALL_ZIP functions/*.sql tables/*.sql views/*.sql full_install.sql
  # Create the incremental installer
- export LATEST_MIGRATION_VERSION=`./maxversion.sh`
- echo "Found latest migration version: $LATEST_MIGRATION_VERSION"
- zip -r -j $INCREMENTAL_INSTALL_ZIP migrations/$LATEST_MIGRATION_VERSION/*.sql
deploy:
  provider: releases
  draft: true
  api_key:
    secure: qVurNxNaTatjAER0EHig4UYPAAYg4EvUbcwoEBRqcpgZRXCtz4bxHNzHn65PRmqYOJNaAjxm8pYfxM/+up7eqABV3vD8q5LOQz42y7Gl6lESq7X+CJ4C9xqW0UEcg6/AiWgQLLM4hceloOEpOQirOTv3+SdCuUdZfREW1lfvFggXQRrFmgX9GU8GsaV59F6XscSHvur0GCKNzrxUwTl8EYWFDmy3+o2xTyLCMM3u8udsLQ76PijcWTT4eXoA6eryW4CGjq9L4QpSorq38lKVlEtxjt1Jo4GeUaOpoyrTy2tgwP9aNnTdLbWov6oRN6R8geVp2gdgV376O5nyJnukxHxlMbtAX8oPNext547WTT8pewv8+JvahasczPHhWku4koRBK7enXFnzkrj2D431SIUhra1BWym6Uk9WU82B8glqmon1BWp2uSh5L7AQ2ys1cZ1NimS9DMJ6e3+o/HBfqFhh+lSKuHhI1m7Q8i8C0uT+nCFNXwotWQ+kFlpWS2CR3zXu/iShOleEt7us1EV7SeEwXRVBua6dFyJIicP7SOlFmA5EbN0vILpVkS0GpSTQZ70k7BTlCakiNRBDj3SfE2RLIpJ3NYLre0+Xh6Of+puRPVmI4a7gJ5ANeVbc60lvHTFFjvCNNQQhOb3vNqdYBp/C3TxQTF3BS2SgyRaaOYE=
  file:
    - "$FULL_INSTALL_ZIP"
    - "$INCREMENTAL_INSTALL_ZIP"
  on:
    repo: palette-software/palette-insight-reporting
    tags: true
  skip_cleanup: true
notifications:
  email:
    on_success: never
    on_failure: never
