alter table p_cpu_usage_bootstrap_rpt rename to p_cpu_usage_bootstrap_rpt_old;
\i 003-up-p_cpu_usage_bootstrap_report.sql
\i 003-up-s_cpu_usage_bootstrap_report.sql
select create_s_cpu_usage_bootstrap_rpt('palette');
insert into s_cpu_usage_bootstrap_rpt select * from p_cpu_usage_bootstrap_rpt_old;
select manage_partitions('palette', 'p_cpu_usage_bootstrap_rpt');

insert into p_cpu_usage_bootstrap_rpt (
		p_id
       , p_cpu_usage_report_p_id
       , cpu_usage_p_id
       , cpu_usage_p_threadinfo_id
       , cpu_usage_ts
       , cpu_usage_ts_rounded_15_secs
       , cpu_usage_ts_date
       , cpu_usage_ts_day_hour
       , cpu_usage_vizql_session
       , cpu_usage_repository_url
       , cpu_usage_user_ip
       , cpu_usage_site_id
       , cpu_usage_workbook_id
       , cpu_usage_cpu_time_consumption_ticks
       , cpu_usage_cpu_time_consumption_seconds
       , cpu_usage_cpu_time_consumption_minutes
       , cpu_usage_cpu_time_consumption_hours
       , cpu_usage_ts_interval_ticks
       , cpu_usage_cpu_core_consumption
       , cpu_usage_memory_usage_bytes
       , cpu_usage_process_name
       , cpu_usage_process_owner
       , cpu_usage_is_allocatable
       , cpu_usage_process_level
       , cpu_usage_is_thread_level
       , cpu_usage_host_name
       , cpu_usage_process_id
       , cpu_usage_thread_id
       , session_start_ts
       , session_end_ts
       , cpu_usage_username
       , cpu_usage_h_workbooks_p_id
       , cpu_usage_h_projects_p_id
       , cpu_usage_publisher_h_users_p_id
       , cpu_usage_publisher_h_system_users_p_id
       , cpu_usage_h_sites_p_id
       , cpu_usage_interactor_h_users_p_id
       , cpu_usage_interactor_h_system_users_p_id
       , cpu_usage_max_reporting_granularity
       , cpu_usage_dataserver_session
       , cpu_usage_parent_vizql_session
       , cpu_usage_parent_dataserver_session
       , cpu_usage_spawned_by_parent_ts
       , cpu_usage_parent_vizql_destroy_sess_ts
       , cpu_usage_parent_process_type
       , site_p_id
       , site_p_filepath
       , site_id
       , site_name
       , site_url_namespace
       , site_status
       , site_created_at
       , site_updated_at
       , site_user_quota
       , site_content_admin_mode
       , site_storage_quota
       , site_metrics_level
       , site_status_reason
       , site_subscriptions_enabled
       , site_custom_subscription_footer
       , site_custom_subscription_email
       , site_luid
       , site_query_limit
       , site_authoring_disabled
       , site_sheet_image_enabled
       , site_livedb_connections_whitelist_enabled
       , site_refresh_token_setting
       , site_version_history_enabled
       , site_p_cre_date
       , site_p_active_flag
       , site_p_valid_from
       , site_p_valid_to
       , project_p_id
       , project_p_filepath
       , project_id
       , project_name
       , project_owner_id
       , project_created_at
       , project_updated_at
       , project_state
       , project_description
       , project_site_id
       , project_special
       , project_luid
       , project_controlled_permissions_enabled
       , project_p_cre_date
       , project_p_active_flag
       , project_p_valid_from
       , project_p_valid_to
       , workbook_p_id
       , workbook_p_filepath
       , workbook_id
       , workbook_name
       , workbook_repository_url
       , workbook_description
       , workbook_created_at
       , workbook_updated_at
       , workbook_owner_id
       , workbook_project_id
       , workbook_view_count
       , workbook_size
       , workbook_embedded
       , workbook_thumb_user
       , workbook_refreshable_extracts
       , workbook_extracts_refreshed_at
       , workbook_lock_version
       , workbook_state
       , workbook_version
       , workbook_checksum
       , workbook_display_tabs
       , workbook_data_engine_extracts
       , workbook_incrementable_extracts
       , workbook_site_id
       , workbook_revision
       , workbook_repository_data_id
       , workbook_repository_extract_data_id
       , workbook_first_published_at
       , workbook_primary_content_url
       , workbook_share_description
       , workbook_show_toolbar
       , workbook_extracts_incremented_at
       , workbook_default_view_index
       , workbook_luid
       , workbook_asset_key_id
       , workbook_document_version
       , workbook_content_version
       , workbook_p_cre_date
       , workbook_p_active_flag
       , workbook_p_valid_from
       , workbook_p_valid_to
       , interactor_s_user_p_id
       , interactor_s_user_p_filepath
       , interactor_s_user_id
       , interactor_s_user_name
       , interactor_s_user_email
       , interactor_s_user_hashed_password
       , interactor_s_user_salt
       , interactor_s_user_sys
       , interactor_s_user_keychain
       , interactor_s_user_domain_id
       , interactor_s_user_friendly_name
       , interactor_s_user_custom_display_name
       , interactor_s_user_activation_code
       , interactor_s_user_activated_at
       , interactor_s_user_state
       , interactor_s_user_admin_level
       , interactor_s_user_created_at
       , interactor_s_user_updated_at
       , interactor_s_user_deleted_at
       , interactor_s_user_auth_user_id
       , interactor_s_user_asset_key_id
       , interactor_s_user_p_cre_date
       , interactor_s_user_p_active_flag
       , interactor_s_user_p_valid_from
       , interactor_s_user_p_valid_to
       , publisher_user_p_id
       , publisher_user_p_filepath
       , publisher_user_id
       , publisher_user_login_at
       , publisher_user_licensing_role_id
       , publisher_user_nonce
       , publisher_user_row_limit
       , publisher_user_storage_limit
       , publisher_user_created_at
       , publisher_user_extracts_required
       , publisher_user_updated_at
       , publisher_user_admin_level
       , publisher_user_publisher_tristate
       , publisher_user_raw_data_suppressor_tristate
       , publisher_user_site_id
       , publisher_user_system_user_id
       , publisher_user_system_admin_auto
       , publisher_user_luid
       , publisher_user_p_cre_date
       , publisher_user_p_active_flag
       , publisher_user_p_valid_from
       , publisher_user_p_valid_to
       , publisher_s_user_p_id
       , publisher_s_user_p_filepath
       , publisher_s_user_id
       , publisher_s_user_name
       , publisher_s_user_email
       , publisher_s_user_hashed_password
       , publisher_s_user_salt
       , publisher_s_user_sys
       , publisher_s_user_keychain
       , publisher_s_user_domain_id
       , publisher_s_user_friendly_name
       , publisher_s_user_custom_display_name
       , publisher_s_user_activation_code
       , publisher_s_user_activated_at
       , publisher_s_user_state
       , publisher_s_user_admin_level
       , publisher_s_user_created_at
       , publisher_s_user_updated_at
       , publisher_s_user_deleted_at
       , publisher_s_user_auth_user_id
       , publisher_s_user_asset_key_id
       , publisher_s_user_p_cre_date
       , publisher_s_user_p_active_flag
       , publisher_s_user_p_valid_from
       , publisher_s_user_p_valid_to
       , session_duration
       , thread_name
       , site_name_id
       , project_name_id
       , site_project
       , workbook_name_id
       , cpu_usage_user_type
       , session_elapsed_seconds
       , p_cre_date
       , currentsheet
)
SELECT  
		p_id
       , p_cpu_usage_report_p_id
       , cpu_usage_p_id
       , cpu_usage_p_threadinfo_id
       , cpu_usage_ts
       , cpu_usage_ts_rounded_15_secs
       , cpu_usage_ts_date
       , cpu_usage_ts_day_hour
       , cpu_usage_vizql_session
       , cpu_usage_repository_url
       , cpu_usage_user_ip
       , cpu_usage_site_id
       , cpu_usage_workbook_id
       , cpu_usage_cpu_time_consumption_ticks
       , cpu_usage_cpu_time_consumption_seconds
       , cpu_usage_cpu_time_consumption_minutes
       , cpu_usage_cpu_time_consumption_hours
       , cpu_usage_ts_interval_ticks
       , cpu_usage_cpu_core_consumption
       , cpu_usage_memory_usage_bytes
       , cpu_usage_process_name
       , cpu_usage_process_owner
       , cpu_usage_is_allocatable
       , cpu_usage_process_level
       , cpu_usage_is_thread_level
       , cpu_usage_host_name
       , cpu_usage_process_id
       , cpu_usage_thread_id
       , session_start_ts
       , session_end_ts
       , cpu_usage_username
       , cpu_usage_h_workbooks_p_id
       , cpu_usage_h_projects_p_id
       , cpu_usage_publisher_h_users_p_id
       , cpu_usage_publisher_h_system_users_p_id
       , cpu_usage_h_sites_p_id
       , cpu_usage_interactor_h_users_p_id
       , cpu_usage_interactor_h_system_users_p_id
       , cpu_usage_max_reporting_granularity
       , cpu_usage_dataserver_session
       , cpu_usage_parent_vizql_session
       , cpu_usage_parent_dataserver_session
       , cpu_usage_spawned_by_parent_ts
       , cpu_usage_parent_vizql_destroy_sess_ts
       , cpu_usage_parent_process_type
       , site_p_id
       , site_p_filepath
       , site_id
       , site_name
       , site_url_namespace
       , site_status
       , site_created_at
       , site_updated_at
       , site_user_quota
       , site_content_admin_mode
       , site_storage_quota
       , site_metrics_level
       , site_status_reason
       , site_subscriptions_enabled
       , site_custom_subscription_footer
       , site_custom_subscription_email
       , site_luid
       , site_query_limit
       , site_authoring_disabled
       , site_sheet_image_enabled
       , site_livedb_connections_whitelist_enabled
       , site_refresh_token_setting
       , site_version_history_enabled
       , site_p_cre_date
       , site_p_active_flag
       , site_p_valid_from
       , site_p_valid_to
       , project_p_id
       , project_p_filepath
       , project_id
       , project_name
       , project_owner_id
       , project_created_at
       , project_updated_at
       , project_state
       , project_description
       , project_site_id
       , project_special
       , project_luid
       , project_controlled_permissions_enabled
       , project_p_cre_date
       , project_p_active_flag
       , project_p_valid_from
       , project_p_valid_to
       , workbook_p_id
       , workbook_p_filepath
       , workbook_id
       , workbook_name
       , workbook_repository_url
       , workbook_description
       , workbook_created_at
       , workbook_updated_at
       , workbook_owner_id
       , workbook_project_id
       , workbook_view_count
       , workbook_size
       , workbook_embedded
       , workbook_thumb_user
       , workbook_refreshable_extracts
       , workbook_extracts_refreshed_at
       , workbook_lock_version
       , workbook_state
       , workbook_version
       , workbook_checksum
       , workbook_display_tabs
       , workbook_data_engine_extracts
       , workbook_incrementable_extracts
       , workbook_site_id
       , workbook_revision
       , workbook_repository_data_id
       , workbook_repository_extract_data_id
       , workbook_first_published_at
       , workbook_primary_content_url
       , workbook_share_description
       , workbook_show_toolbar
       , workbook_extracts_incremented_at
       , workbook_default_view_index
       , workbook_luid
       , workbook_asset_key_id
       , workbook_document_version
       , workbook_content_version
       , workbook_p_cre_date
       , workbook_p_active_flag
       , workbook_p_valid_from
       , workbook_p_valid_to
       , interactor_s_user_p_id
       , interactor_s_user_p_filepath
       , interactor_s_user_id
       , interactor_s_user_name
       , interactor_s_user_email
       , interactor_s_user_hashed_password
       , interactor_s_user_salt
       , interactor_s_user_sys
       , interactor_s_user_keychain
       , interactor_s_user_domain_id
       , interactor_s_user_friendly_name
       , interactor_s_user_custom_display_name
       , interactor_s_user_activation_code
       , interactor_s_user_activated_at
       , interactor_s_user_state
       , interactor_s_user_admin_level
       , interactor_s_user_created_at
       , interactor_s_user_updated_at
       , interactor_s_user_deleted_at
       , interactor_s_user_auth_user_id
       , interactor_s_user_asset_key_id
       , interactor_s_user_p_cre_date
       , interactor_s_user_p_active_flag
       , interactor_s_user_p_valid_from
       , interactor_s_user_p_valid_to
       , publisher_user_p_id
       , publisher_user_p_filepath
       , publisher_user_id
       , publisher_user_login_at
       , publisher_user_licensing_role_id
       , publisher_user_nonce
       , publisher_user_row_limit
       , publisher_user_storage_limit
       , publisher_user_created_at
       , publisher_user_extracts_required
       , publisher_user_updated_at
       , publisher_user_admin_level
       , publisher_user_publisher_tristate
       , publisher_user_raw_data_suppressor_tristate
       , publisher_user_site_id
       , publisher_user_system_user_id
       , publisher_user_system_admin_auto
       , publisher_user_luid
       , publisher_user_p_cre_date
       , publisher_user_p_active_flag
       , publisher_user_p_valid_from
       , publisher_user_p_valid_to
       , publisher_s_user_p_id
       , publisher_s_user_p_filepath
       , publisher_s_user_id
       , publisher_s_user_name
       , publisher_s_user_email
       , publisher_s_user_hashed_password
       , publisher_s_user_salt
       , publisher_s_user_sys
       , publisher_s_user_keychain
       , publisher_s_user_domain_id
       , publisher_s_user_friendly_name
       , publisher_s_user_custom_display_name
       , publisher_s_user_activation_code
       , publisher_s_user_activated_at
       , publisher_s_user_state
       , publisher_s_user_admin_level
       , publisher_s_user_created_at
       , publisher_s_user_updated_at
       , publisher_s_user_deleted_at
       , publisher_s_user_auth_user_id
       , publisher_s_user_asset_key_id
       , publisher_s_user_p_cre_date
       , publisher_s_user_p_active_flag
       , publisher_s_user_p_valid_from
       , publisher_s_user_p_valid_to
       , session_duration
       , thread_name
       , site_name_id
       , project_name_id
       , site_project
       , workbook_name_id
       , cpu_usage_user_type
       , session_elapsed_seconds
       , p_cre_date
       , currentsheet
 FROM s_cpu_usage_bootstrap_rpt;
 
 drop table p_cpu_usage_bootstrap_rpt_old;