CREATE TABLE h_datasources
(
	p_id bigserial,
	p_filepath text,
	id integer,
	name character varying(255),
	repository_url text,
	owner_id integer,
	created_at timestamp without time zone,
	updated_at timestamp without time zone,
	project_id integer,
	size bigint,
	lock_version integer,
	state character varying(32),
	db_class text,
	db_name text,
	table_name text,
	site_id integer,
	revision character varying(255),
	repository_data_id bigint,
	repository_extract_data_id bigint,
	embedded text,
	incrementable_extracts boolean,
	refreshable_extracts boolean,
	data_engine_extracts boolean,
	extracts_refreshed_at timestamp without time zone,
	first_published_at timestamp without time zone,
	connectable boolean,
	is_hierarchical boolean,
	extracts_incremented_at timestamp without time zone,
	luid character varying(166),
	asset_key_id integer,
	document_version character varying(255),
	description text,
	content_version integer,
	parent_workbook_id integer,
	hidden_name character varying(255),
	last_published_at timestamp without time zone,
	p_cre_date timestamp without time zone default now(),
	p_active_flag CHARACTER VARYING(1),
	p_valid_from timestamp without time zone,
	p_valid_to timestamp without time zone
)
DISTRIBUTED BY (p_id);


