CREATE TABLE h_workbooks
(
	p_id bigserial,
	p_filepath text,
	id integer,
	name character varying(255),
	repository_url text,
	description text,
	created_at timestamp without time zone,
	updated_at timestamp without time zone,
	owner_id integer,
	project_id integer,
	view_count integer,
	size bigint,
	embedded text,
	thumb_user integer,
	refreshable_extracts boolean,
	extracts_refreshed_at timestamp without time zone,
	lock_version integer,
	state character varying(32),
	version character varying(255),
	checksum character varying(255),
	display_tabs boolean,
	data_engine_extracts boolean,
	incrementable_extracts boolean,
	site_id integer,
	revision character varying(255),
	repository_data_id bigint,
	repository_extract_data_id bigint,
	first_published_at timestamp without time zone,
	primary_content_url character varying(255),
	share_description character varying(255),
	show_toolbar boolean,
	extracts_incremented_at timestamp without time zone,
	default_view_index integer,
	luid character varying(166),
	asset_key_id integer,
	document_version character varying(255),
	content_version integer,
	last_published_at timestamp without time zone,
	p_cre_date timestamp without time zone default now(),
	p_active_flag CHARACTER VARYING(1),
	p_valid_from timestamp without time zone,
	p_valid_to timestamp without time zone
)
	WITH (appendonly=true, orientation=row, compresstype=quicklz)
DISTRIBUTED BY (p_id);


